Plug 'nelstrom/vim-textobj-rubyblock'
Plug 'AndrewRadev/splitjoin.vim'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-rails'
Plug 'honza/vim-snippets'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-dispatch'
Plug 'thoughtbot/vim-rspec'
Plug 'radenling/vim-dispatch-neovim'
Plug 'ecomba/vim-ruby-refactoring'

" Makes file navigation too slow
"Plug 'sentientmonkey/vim-flog'
