#!/bin/bash

set -e

list_of_files=$(git status --short | grep '\.rb' | awk '{print $2}')

for filename in $list_of_files
do
  echo $filename
  rub_command="rubocop $filename | grep 'offenses'"
  eval $rub_command
done
