set rtp+=~/.vim/bundle/Vundle.vim
filetype off

call vundle#begin()

  Plugin 'gmarik/Vundle.vim'
  Plugin 'mattn/emmet-vim'
  Plugin 'tomasr/molokai'
  Bundle 'VimClojure'
  Bundle 'geoffharcourt/vim-matchit'

  Plugin 'bling/vim-airline'
  Plugin 'tacahiroy/ctrlp-funky'
  Bundle "scrooloose/nerdtree"

" Code Completion"
  Plugin 'AndrewRadev/splitjoin.vim'
  Plugin 'Raimondi/delimitMate', { 'on': [] }
  Plugin 'SirVer/ultisnips', { 'on': [] }
  Plugin 'Valloric/YouCompleteMe', { 'do': './install.sh', 'on': [] }
  Plugin 'honza/vim-snippets', { 'on': [] }
  Plugin 'marijnh/tern_for_vim', { 'for': 'javascript' }
  Plugin 'tpope/vim-commentary', { 'on': '<Plug>Commentary' }
  Plugin 'tpope/vim-repeat'
  Plugin 'tpope/vim-surround'

call vundle#end()

filetype plugin indent on

filetype on

source ~/dotfiles/vim/init
source ~/dotfiles/vim/ui
source ~/dotfiles/vim/functions
source ~/dotfiles/vim/plugins
source ~/dotfiles/vim/maps
source ~/dotfiles/vim/statusline
