source ~/dotfiles/nvim/plugins/init.vim

source ~/dotfiles/nvim/init
source ~/dotfiles/nvim/ui

for f in split(glob('~/dotfiles/nvim/functions/*'), '\n')
    exe 'source' f
endfor

source ~/dotfiles/nvim/maps
